on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Install Qt and build
        run: |
          brew install -y cmake make ninja
          pip install aqtinstall
          mkdir -p ./qt-install
          cd ./qt-install
          aqt install-qt mac desktop 6.8.2 clang_64 -m all
          export Qt6_DIR=$(pwd)/6.8.2/macos/
          export QT_PLUGIN_PATH=$(pwd)/6.8.2/macos/plugins
          export PKG_CONFIG_PATH=$(pwd)/6.8.2/macos/lib/pkgconfig
          export QML2_IMPORT_PATH=$(pwd)/6.8.2/macos/qml
          export PATH="$(pwd)/6.8.2/macos/bin:$PATH"
          cd ../
          git clone --depth=1 -bdevelopment --recursive --single-branch https://github.com/ahrm/sioyek.git
          cd ./sioyek
          chmod +x ./build_mac.sh
          MAKE_PARALLEL=8 ./build_mac.sh
      - name: Upload binary
        uses: actions/upload-artifact@v7
        with:
          name: sioyek-binary
          path: ./sioyek/build/sioyek.app
          if-no-files-found: error
          archive: false
